### PR TITLE
Bump version: 4.0.0 → 4.0.1

### PR DESCRIPTION
**Pull request by aryabharat**
Add URL type for convet_url function for stix 1.x

Reference issue: https://github.com/oasis-open/cti-stix-slider/issues/65

### CODE REVIEW

**Comment by rpiazza** [comment]
@aryabharat - please merge in the master branch.  It should allow the "checks" pass

**Comment by aryabharat** [comment]
@rpiazza I have update the branch.

**Comment by rpiazza** [comment]
There is a problem with the github actions - they are failing.  I know what needs to be done, but I have to get the admin of the OASIS-OPEN repo to do it.  Hopefully, we can get this done soon.

**Comment by rpiazza** [comment]
Hi @aryabharat,

I think if you fix the pre-commit error below - I will be able to do the merge:

tox: pre-commit-check
  pre-commit-check: commands[0]> pre-commit run --all-files
  
  trim trailing whitespace.................................................Passed
  check for merge conflicts................................................Passed
  Check project styling....................................................Failed
  - hook id: flake8
  - exit code: 1
  
  stix2slider/convert_pattern.py:818:1: E302 expected 2 blank lines, found 1
  
  Sort python imports (shows diff).........................................Passed
  Sort python imports (fixes files)........................................Passed

**Comment by rpiazza** [comment]
@aryabharat - nevermind - I will take care of it...

**Comment by aryabharat** [comment]
> @aryabharat - nevermind - I will take care of it...

Thanks @rpiazza

**Pull request merged**
