### PR TITLE
Add ability to override default 'example' namespace.

### PR DESCRIPTION
**Pull request by emmanvg**
Related to #32 

Added `--use-namespace` option.

### CODE REVIEW

**Review by gtback — APPROVED** [review]
This looks good to me. Is there any good way to test this? If so, let's add that, but otherwise I think this can be merged.

**Comment by rpiazza** [comment]
@emmanvg @gtback:  Hold off on merging this - I made some changes too that haven't been pushed, which I think conflict with what was done here.

**Comment by rpiazza** [comment]
@emmanvg: your changes subsume mine, so we should just merge this in and I will delete my branch.
One thing - can you add --use-namespace to command-line.rst, then it will be ready for merging.

**Comment by emmanvg** [comment]
@rpiazza @gtback, it should be good to go now. I have added a test as well.

**Pull request merged**
