### PR TITLE
Add infrastructure and fix minor issues

### PR DESCRIPTION
**Pull request by jaysneg**
Implementation of:
* Infrastructure SDO & relationships
* Fix process_relationships processing for TTP-to-TTP relationships
* Fix attack pattern relationship typo

### CODE REVIEW

**Comment by rpiazza** [comment]
Hi @jaysneg,

Thanks for this pull request!  I'm sure we will incorporate it into the slider when we update it to handle the latest working draft of the STIX 2.1 spec!

**Comment by jaysneg** [comment]
Hi,
is there any TODO list for STIX 2.1 support?

**Comment by rpiazza** [comment]
@jaysneg 

No formal TODO list...  Probably in the new year I will just put out a new version to conform to the latest working draft - which should be the final version of 2.1

**Comment by rpiazza** [comment]
Similar changes made in other commits

**Pull request closed without merging**
