### PR TITLE
Remove unnecessary files

### PR DESCRIPTION
**Pull request by emmanvg**

### CODE REVIEW

**Comment by emmanvg** [comment]
Removes __pycache__/ directories and some .DStore files

**Comment by gtback** [comment]
Can you add a .gitignore so they don't get re-added?

**Comment by rpiazza** [comment]
There is one there...

**Comment by gtback** [comment]
Oh, nevermind, I didn't actually look at the current repo, just this PR :-( My fault.

I remembered seeing the .pyc files in your first commit, @rpiazza , and didn't realize you added another commit right after that added the .gitignore.

**Review by gtback — APPROVED** [review]

**Pull request merged**
